Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-07, with the labels that each got.

#43 [KOGITO-7483] Setup quarkus update job
  .ci/jenkins/dsl/jobs.groovy
Labels: Infrastructure

#49 KOGITO-7464: Home Page for Serverless Workflow Guides
  antora/supplemental-ui/css/home.css
  antora/supplemental-ui/partials/head-meta.hbs
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: SMEs Review

#47 KOGITO-7313 Added "Mocking OpenAPI services with WireMock" guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-opnapi-services-with-wiremock.adoc
Labels: Needs Docs Review

#63 KOGITO-7314: Patch PR for KOGITO-7313 with doc improvements
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-opnapi-services-with-wiremock.adoc
Labels: Docs Review

#29 KOGITO-7263: [KSW-Guides] Orchestrating third party services with OAuth2 authentication
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/security/orchestrating-third-party-services-with-oauth2/architecture-diagram.png
  serverlessworkflow/modules/ROOT/assets/images/security/orchestrating-third-party-services-with-oauth2/currency-exchange-workflow-diagram.png
  serverlessworkflow/modules/ROOT/assets/images/security/orchestrating-third-party-services-with-oauth2/currency-exchange-workflow-diagram.svg
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
Labels: Needs Docs Review

#67 KOGITO-7300: Patch PR for KOGITO-7299 with doc improvements in dashboard doc
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/integrations/serverless-dashboard-with-runtime-data.adoc
Labels: Docs Review

#71 KOGITO-7264: Patch PR for KOGITO-7263 with doc improvements in OAuth2 authentication guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
Labels: Docs Review

#46 [KOGITO-7255] Callback guide
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
Labels: Needs Docs Review

#69 [KOGITO-7324] - Add the CONTRIBUTIONS.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.adoc
Labels: Infrastructure

#37 [KOGITO-6806] [KSW-Guides] Serverless Workflow with the Saga example
  serverlessworkflow/modules/ROOT/assets/images/use-cases/orchestration-based-saga-pattern/order-fulfillment-example.png
  serverlessworkflow/modules/ROOT/assets/images/use-cases/orchestration-based-saga-pattern/order-fulfillment-saga-workflow.png
  serverlessworkflow/modules/ROOT/assets/images/use-cases/orchestration-based-saga-pattern/order-fulfillment-saga.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/use-cases/orchestration-based-saga-pattern.adoc
Labels: Needs Docs Review

#70 KOGITO-7593 Referred getting started in prereqs and fixed typos
  serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
  serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-openapi-services-with-wiremock.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
Labels: bug :bug:

#73 Add issues templates for enhancement and bugs
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: Infrastructure :gear:

#55 KOGITO-7311: Mocking HTTP CloudEvents sink with Wiremock
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/example-components-interaction.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/order-example-worflows.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/testing-eventing-sink.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
Labels: Needs Docs Review

#79 KOGITO-7630 Added a reminder to include a card for a new guide to CON…
  CONTRIBUTING.md
Labels: Infrastructure :gear:

#56 Updating the home page with all cards about to be published
  .github/pull_request_template.md
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Infrastructure :gear:

#80 KOGITO-7312: Patch PR for KOGITO-7311 with doc improvements in Mocking HTTP CloudEvents sink with Wiremock guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
Labels: Docs Review :memo:

#77 KOGITO-6996 Added new guide: "Working with parallelism"
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Needs Docs Review

#76 KOGITO-7244: Patch PR for KOGITO-6806 with doc improvements in Saga example guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/use-cases/orchestration-based-saga-pattern.adoc
Labels: Docs Review :memo:

#72 KOGITO-7256: Patch PR for KOGITO-7255 with doc improvements in Callback guide
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
Labels: Docs Review :memo:

#82 KOGITO-7248: Patch PR for KOGITO-6996 with doc improvements in parallelism guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#54 [KOGITO-7286] Configuring events with Kafka
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
Labels: Needs Docs Review

#88 KOGITO-7287: Patch PR for KOGITO-7286 with doc improvements in Consuming and producing events with Kafka guide
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#34 KOGITO-7309 Integration tests with PostgreSQL
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/integration-tests-with-postgresql.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
Labels: Needs Docs Review

#89 KOGITO-7664 Fix wrong name of property in text (`substractvalue` -> `subtractValue`)
  serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
Labels: SMEs Review

#91 KOGITO-7310: Patch PR for KOGITO-7309 with doc improvements in Integration tests with PostgreSQL guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/integration-tests-with-postgresql.adoc
Labels: Docs Review :memo:

#75 KOGITO-7301 - Persistence with PostgresSQL databases
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
Labels: Needs Docs Review, PRIO

#96 KOGITO-7302: Patch PR for KOGITO-7301 with doc improvements in Persistence with PostgresSQL databases guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
Labels: Docs Review :memo:
