Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-10, with the labels that each got.

#198 [KOGITO-7764] Timeout support
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/core/callback-state-timeouts.svg
  serverlessworkflow/modules/ROOT/assets/images/core/jobs-service-knative-architecture.png
  serverlessworkflow/modules/ROOT/assets/images/core/switch-state-timeouts.svg
  serverlessworkflow/modules/ROOT/assets/images/core/timeout-switch-wokflow-ui.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#215 KOGITO-7967 Improve clarity of procedure to start gRPC application in the guide
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
Labels: Docs Review :memo:

#229 Docs Patch PR for KOGITO-7967: Improve clarity of procedure to start gRPC application in the guide
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
Labels: Docs Review :memo:

#224 DSL: Correct setup branch job
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: Infrastructure :gear:

#228 KOGITO-8110 Correct GHA DSL checks
  .ci/jenkins/dsl/test.sh
  .github/workflows/cherry-pick.yml
  .github/workflows/jenkins-tests-PR.yml
  .github/workflows/sw-docs-pr.yml
Labels: Infrastructure :gear:

#232 Orchestrating third party services with oauth2 updates
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
Labels: SMEs Review

#223 [KOGITO-7951] Adding custom types through addons
  serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
Labels: SMEs Review, Docs Review :memo:

#238 Docs Patch PR for KOGITO-8078: Document adding custom type through addon
  serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
Labels: Docs Review :memo:

#243 [KOGITO-8159] Event state not starting state if exclusive=false
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
Labels: Docs Review :memo:
