Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-08, with the labels that each got.

#84 KOGITO-7636 SW configuration properties guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: SMEs Review, PRIO

#99 KOGITO-7637: Patch PR for KOGITO-7636 with doc improvements in configuration properties
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#81 [KOGITO-7610] - Adding downstream content to upstream
  .github/CODEOWNERS
  package-lock.json
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
Labels: Infrastructure :gear:, PRIO

#92 KOGITO-6998 Added configuring-openapi-services-endpoints guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
Labels: Needs Docs Review, PRIO

#102 KOGITO-7245: Patch PR for KOGITO-6998 with doc improvements in Configuring OpenAPI services endpoints guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
Labels: Docs Review :memo:

#94 [KOGITO-7267] - Consuming and producing events on Knative Eventing
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
Labels: Needs Docs Review, PRIO

#107 KOGITO-7268: Patch PR for KOGITO-7267 with doc improvements in Consuming and producing events on Knative Eventing guide
  serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#111 [KOGITO-7708] Fix references and missing attributes
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
Labels: Needs Docs Review, Infrastructure :gear:

#113 [KOGITO-7269] [KSW-Guides] Getting familiar with our tooling
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
Labels: Needs Docs Review, PRIO

#115 KOGITO-7270: Patch PR for KOGITO-7269 with doc improvements in tooling guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#114 KOGITO-7292: Patch PR for KOGITO-7290 with doc improvements in Handling events on workflows guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/handling-events-on-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#127 Small fix in orchestrating-third-party-services-with-oauth2.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
Labels: Needs Cherry Pick :cherries:

#130 KOGITO-7589 & KOGITO-7707: Product name changes and sanity check fixes
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
  serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
  serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
  serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
  serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/handling-events-on-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/integrations/serverless-dashboard-with-runtime-data.adoc
  serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
  serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
  serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
  serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/integration-tests-with-postgresql.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-openapi-services-with-wiremock.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
  serverlessworkflow/modules/ROOT/pages/use-cases/orchestration-based-saga-pattern.adoc
Labels: Docs Review :memo:, Needs Cherry Pick :cherries:

#128 Updating RHBQ procedure
  serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
Labels: Needs Cherry Pick :cherries:

#120 Fixes after Cloud guides review
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Labels: Needs Cherry Pick :cherries:

#85 [KOGITO-7288] [KSW-Guides] Event correlation with workflows
  serverlessworkflow/modules/ROOT/assets/images/eventing/correlation.sw.json.png
  serverlessworkflow/modules/ROOT/assets/images/eventing/event-correlation-evaluation-flow.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/event-correlation-with-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Needs Cherry Pick :cherries:

#136 [1.24.x] RHBQ Procedure / Fix after Cloud guides review
  serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Labels: cherry-pick :cherries:

#137 [1.25.x] RHBQ Procedure / Fix after Cloud guides review
  serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Labels: cherry-pick :cherries:

#138 [1.26.x] RHBQ Procedure / Fix after Cloud guides review
  serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Labels: cherry-pick :cherries:

#139 [1.24.x] [KOGITO-7288] [KSW-Guides] Event correlation with workflows
  serverlessworkflow/modules/ROOT/assets/images/eventing/correlation.sw.json.png
  serverlessworkflow/modules/ROOT/assets/images/eventing/event-correlation-evaluation-flow.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/event-correlation-with-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: cherry-pick :cherries:

#140 [1.25.x][KOGITO-7288] [KSW-Guides] Event correlation with workflows
  serverlessworkflow/modules/ROOT/assets/images/eventing/correlation.sw.json.png
  serverlessworkflow/modules/ROOT/assets/images/eventing/event-correlation-evaluation-flow.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/event-correlation-with-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: cherry-pick :cherries:

#146 [1.25.x] - Fix RHBQ procedure, add image procedure
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-post-create-project.adoc
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#147 [1.26.x] - Fix RHBQ procedure, add image procedure
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-post-create-project.adoc
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#135 KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: Needs Docs Review, Needs Cherry Pick :cherries:

#142 [1.24.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#154 [1.24.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs
  antora-playbook-author.yml
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
Labels: cherry-pick :cherries:

#153 [1.25.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs
  antora-playbook-author.yml
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
Labels: cherry-pick :cherries:

#152 [1.26.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs
  antora-playbook-author.yml
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
Labels: cherry-pick :cherries:

#155 [KOGITO-7761] Fix snapshot, latest versions and ref URLs
  antora-playbook-author.yml
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
Labels: SMEs Review, Infrastructure :gear:, PRIO, Needs Cherry Pick :cherries:

#157 [KOGITO-7767] - Fix Maven instructions to add earlyaccess config
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: PRIO, Needs Cherry Pick :cherries:

#149 [1.25.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#150 [1.26.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#164 [1.26.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#163 [1.25.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#161 [1.24.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: cherry-pick :cherries:

#151 KOGITO-7259- [KSW-Guides] Defining an input schema for Workflows
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Needs Docs Review

#168 KOGITO-7260: Patch PR for KOGITO-7250 with doc improvements in input schema guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:

#169 add published docs link on the readme
  README.adoc
Labels: backport-1.24.x

#174 Adding QE to code owners
  .github/CODEOWNERS
Labels: Infrastructure :gear:

#160 KOGITO-7422 [KSW-Guides] Serverless Logic Web Tools
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-create.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deployment-page.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-feature-preview.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-repo.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-openshift-deployments.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-openshift-info.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-openshift-project.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-overview.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-logic-web-tools/serverless-logic-web-tools-workflow-editor.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-enable-kogito-swf-visualization.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-openshift-integration.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
Labels: Needs Docs Review

#175 Add Release notes for 1.26 and contrib guides
  CONTRIBUTING.md
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Labels: Needs Docs Review, backport-1.26.x

#181 Fix cherry-pick label in GHA
  .github/workflows/cherry-pick.yml
Labels: Infrastructure :gear:

#179 KOGITO-7860 Fix the `stock-portfolio-service` name
  serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
Labels: backport-1.26.x
