Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-11, with the labels that each got.

#251 [1.30.x] Update version jenkinsfiles
  .ci/jenkins/Jenkinsfile.post-release
  .ci/jenkins/Jenkinsfile.setup-branch
Labels: backport-main

#226 Update dev ui start workflow page
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-fail-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-success-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-fail-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-success-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-values.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-events-custom-form.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-events.png
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
Labels: Docs Review :memo:, backport-1.30.x

#242 Update swf diagram docs
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-details-page.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-diagram-panel.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instance-completed.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-mermaid-diagram-panel.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-stunner-diagram-panel.png
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
Labels: SMEs Review, backport-1.30.x
