Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-12, with the labels that each got.

#256 [KOGITO-7282] - [KSW-Guides] Deploying on Kubernetes Clusters
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-images-with-kn-cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_create_namespace_and_deploy_info.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_deploy_workflow_application_requisites.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_prerequisites.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_proc_deploy_sw_kn_cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_proc_deploy_sw_kubectl.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_verify_if_swf_is_deployed.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-kubernetes-cluster.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-kubernetes.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Labels: SMEs Review, backport-1.32.x

#230 KOGITO-8062 DSL: Refactor environments and export to config
  .ci/jenkins/dsl/jobs.groovy
Labels: Infrastructure :gear:

#269 [KOGITO-8353] Introduce Camel Routes integration guide
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/_common-content/camel-valid-responses.adoc
  serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/integrations/camel-routes-integration.adoc
Labels: SMEs Review
