Repository apache/incubator-kie-kogito-docs, pull requests merged in 2022-09, with the labels that each got.

#189 [main] Bump Quarkus version to 2.12.1.Final
  serverlessworkflow/antora.yml
Labels: Infrastructure :gear:

#187 KOGITO-7849: Patch PR for KOGITO-7422 with doc improvements in serverless logic web tools guides
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-enable-kogito-swf-visualization.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-openshift-integration.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
Labels: Docs Review :memo:

#186 Updating CNCF Custom Functions Guide
  serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
Labels: backport-1.27.x

#177 [KOGITO-7481] - [KWS-Guides] Document the Enhanced Service Discovery
  serverlessworkflow/modules/ROOT/assets/images/cloud/sw-discovery-flow.jpg
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Needs Docs Review

#195 Update kubernetes-service-discovery.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
Labels: backport-1.27.x

#194 KOGITO-7910: Patch PR for Kubernetes service discovery guide with doc improvements
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: Docs Review :memo:, backport-1.27.x

#57 KOGITO-7297: [KSW-Guides] Exposing the workflow base metrics to Prometheus
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/integrations/expose-metrics-to-prometheus.adoc
Labels: Docs Review :memo:, backport-1.27.x

#202 [KOGITO-7841] - update sw-discovery-flow.jpg
  serverlessworkflow/modules/ROOT/assets/images/cloud/sw-discovery-flow.jpg
Labels: backport-1.27.x

#201 KOGITO-7298: Patch PR for KOGITO-7297 with doc improvement to exposing workflow metrics guide
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/integrations/expose-metrics-to-prometheus.adoc
Labels: Docs Review :memo:, backport-1.27.x

#197 KOGITO-7944 Fix `:knative_eventing_doc_url:` extra '/' and broken link
  serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
Labels: backport-1.27.x

#209 Templating release notes for snapshot versions
  serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Labels: SMEs Review, Needs Docs Review, Infrastructure :gear:

#205 KOGITO-7053: SWF Viewer - Community Documentation
  serverlessworkflow/modules/ROOT/assets/images/core/error_handling.png
  serverlessworkflow/modules/ROOT/assets/images/core/expression_diagram.png
  serverlessworkflow/modules/ROOT/assets/images/core/switch_condition.png
  serverlessworkflow/modules/ROOT/assets/images/getting-started/hello-world-workflow.png
  serverlessworkflow/modules/ROOT/assets/images/security/orchestrating-third-party-services-with-oauth2/currency-exchange-workflow-diagram.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-example.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-vscode-command-palette.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-vscode-extension-page.png
  serverlessworkflow/modules/ROOT/assets/images/use-cases/orchestration-based-saga-pattern/order-fulfillment-saga-workflow.png
Labels: SMEs Review

#208 [1.28.x] - Release Notes for 1.28.x
  serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Labels: SMEs Review
