Repository apache/incubator-kie-kogito-docs, pull requests merged in 2023-06, with the labels that each got.

#291 KOGITO-8303: [SWF Dev UI] Add support for starting workflows using gateway API and cloud events
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-filters-in-workflow-instances.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-form.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-no-form.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-start-error-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-start-success-alert.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-events-custom-form.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-events.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-definitions.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event-failure.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event-success.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-empty.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-filters.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-kebab.png
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
Labels: backport-1.39.x

#341 KOGITO-9057 Remove Streams for Apache Kafka content from Serverless Logic Web Tools
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
Labels: backport-1.39.x

#369 [KOGITO-9315] Updating docs to include Kogito Kubernetes Add-on to Discovery
  serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
Labels: backport-1.40.x

#371 [1.40.x] Release Notes for 1.40.0.Final
  CONTRIBUTING.md
  serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Labels: DO_NOT_MERGE :no_good:

#377 some warning fixes
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/common/_common_proc_deploy_kubectl_oc.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_prerequisites.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_proc_deploy_sw_kn_cli.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/quarkus/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
Labels: backport-1.40.x
