Repository apache/incubator-kie-kogito-docs, pull requests merged in 2023-07, with the labels that each got.

#381 [KOGITO-9464] Update Operator Guides and Use Cases
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/referencing-resource-files.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/workflow-status-conditions.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
Labels: backport-1.40.x

#383 [KOGITO-9468] Describing Output schema
  serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
Labels: backport-1.40.x

#384 KOGITO-9451 Reorganize SonataFlow Tooling Guides TOC
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-dashboard-details.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-dashboard-list.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-dashboard-storage-path.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-filters-in-dashboards.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-quarkus-dev-ui.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-fail-alert.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-form.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-no-form.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-start-workflow-success-alert.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-start-error-alert.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-event-start-success-alert.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-trigger-cloud-events.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-definitions-filter.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-definitions.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-details-page.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-details-panel.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instance-completed.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event-failure.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event-success.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-cloud-event.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-empty.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-filters.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-instances-kebab.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-mermaid-diagram-panel.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-stunner-diagram-panel.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-timeline-panel.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-variables-panel.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/common/_prerequisites.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/quarkus/deploying-on-openshift.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-custom-dashboard-page.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
Labels: backport-1.40.x, backport-1.41.x

#382 KOGITO-9427: Adjustments in the SW guides for the Timeouts topic
  serverlessworkflow/modules/ROOT/assets/images/core/jobs-service-knative-architecture.png
  serverlessworkflow/modules/ROOT/assets/images/core/timeout-switch-wokflow-ui.png
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/TimeoutsShowcaseExtendedAchitecture.drawio
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/callback-state-incoming-event.png
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/callback-state-timeouts-decorated.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/callback-state-timeouts.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/event-state-timeouts-decorated.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/event-state-timeouts.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/switch-state-timeouts-decorated.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/switch-state-timeouts.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/timeouts-showcase-extended-architecture.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
  serverlessworkflow/modules/ROOT/pages/use-cases/timeout-showcase-example.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod

#392 [KOGITO-9244] spec.platform.baseImage does not update the Dockerfile …
  serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
Labels: backport-1.41.x

#395 Updating operator tags
  serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/referencing-resource-files.adoc
Labels: backport-main, backport-1.41.x, backport-1.40.x-prod

#415 CI: Fix set `operator_version` attribute
  .ci/jenkins/Jenkinsfile.post-release
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod
