Repository apache/incubator-kie-kogito-docs, pull requests merged in 2023-09, with the labels that each got.

#421 KOGITO-9455: Create the getting started guide to describe how to run …
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x, backport-1.43.x

#432 KOGITO-9460: Create a new guide describing the workflow CLI
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x, backport-1.43.x

#419 [KOGITO-9600][KSW-Guides]: Update chrome extension docs
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-in-github-edit.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-in-github-pr.gif
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-in-github-readonly.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-in-github.png
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
Labels: backport-1.42.x, backport-1.43.x

#441 KOGITO-9682: Add the workflow-timeout SW to the timeouts-showcase Documentation
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/workflow-timeouts-decorated.svg
  serverlessworkflow/modules/ROOT/assets/images/use-cases/timeouts-showcase/workflow-timeouts.svg
  serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
  serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc
  serverlessworkflow/modules/ROOT/pages/use-cases/timeout-showcase-example.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x, backport-1.43.x, backport-1.44.x

#473 [KOGITO-9184] Describing how to pass args and envs to the SonataFlow build process
  serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
Labels: backport-1.44.x

#472 KOGITO-9757 Changed property expansion to use ${property_name}
  serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
Labels: backport-1.44.x

#501 :pencil: Update Operator Roadmap for 1.44+
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
Labels: backport-1.44.x
