Repository apache/incubator-kie-kogito-docs, pull requests merged in 2023-01, with the labels that each got.

#273 [KOGITO-8408] Copying latest to numbered version
  .github/workflows/npm-publish-pages.yml
  scripts/copy-latest.py
Labels: SMEs Review

#183 Adding Postgres DB migration guide
  antora/supplemental-ui/css/home.css
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
  serverlessworkflow/modules/ROOT/pages/persistence/postgresql-flyway-migration.adoc
Labels: SMEs Review, backport-1.32.x

#264 [1.32.x] KOGITO-7676: Added Flyway to release notes
  serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Labels: on-hold

#265 [KOGITO-8314] [KSW-Guides] Using Serverless Operator to deploy workfl…
  .ci/jenkins/Jenkinsfile.post-release
  .ci/jenkins/Jenkinsfile.setup-branch
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/build-and-deploy-with-serverless-operator-on-kubernetes.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: backport-1.32.x

#279 [main] [KOGITO-8495] Bump quarkus version to 2.16.0.Final
  serverlessworkflow/antora.yml
Labels: backport-1.33.x

#268 [KOGITO-8250]-Working with Open API callbacks
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/eventing/openapi-callback.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/eventing/working-with-openapi-callbacks.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: SMEs Review, backport-1.32.x

#283 Remove unnecessary quarkus-container-jib extension
  serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
Labels: SMEs Review, backport-1.33.x

#287 [KOGITO-8249] Updating timeouts guide
  serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
  serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
Labels: SMEs Review
