Repository apache/incubator-kie-kogito-docs, pull requests merged in 2023-08, with the labels that each got.

#425 Update operator installation instructions to new prefix
  serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x

#409 KOGITO-8740: data-index documentation
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-addon.drawio
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-addon.png
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-dev-service.drawio
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-dev-service.png
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-distributions.png
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-graphql-ui.png
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-standalone-service.drawio
  serverlessworkflow/modules/ROOT/assets/images/data-index/data-index-standalone-service.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/data-index/data-index-core-concepts.adoc
  serverlessworkflow/modules/ROOT/pages/data-index/data-index-quarkus-extension.adoc
  serverlessworkflow/modules/ROOT/pages/data-index/data-index-service.adoc
  serverlessworkflow/modules/ROOT/pages/index.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x

#399 KOGITO-9599 Review VS Code extension guide
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-vscode-market-place.png
  serverlessworkflow/modules/ROOT/assets/images/tooling/serverless-workflow-editor/swf-editor-vscode-marketplace.png
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x

#443 Remove specVersion property from example
  serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x

#427 [KOGITO-9218] - Update SonataFlowPlatform struct
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/migration-guide.adoc
Labels: backport-1.42.x

#398 KOGITO-9459 Review Dev UI extension guide
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-monitoring-summary.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-monitoring-workflows.png
  serverlessworkflow/modules/ROOT/assets/images/testing-and-troubleshooting/quarkus-dev-ui-extension/kogito-swf-tools-workflow-details-page.png
  serverlessworkflow/modules/ROOT/nav.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-custom-dashboard-page.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-monitoring-page.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
  serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
  serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x

#450 KOGITO-9668: SWF Editor - In VSCode the diagram reloads if a user clicks on any area of the canvas
  serverlessworkflow/antora.yml
Labels: backport-1.42.x, backport-1.43.x

#460 [KOGITO-9683] - Update Operator's installation guide to reflect OLM
  antora-playbook-author.yml
  antora-playbook.yml
  serverlessworkflow/antora.yml
  serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
  serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
Labels: backport-1.40.x, backport-1.41.x, backport-1.40.x-prod, backport-1.42.x, backport-1.43.x
